### ISSUE TITLE
Can I run the server locally?

### ISSUE THREAD

**Issue by nkaramolegos** [kbaggen/SPINDELMATE#6]
Hello nice job. Can I maintain the log server locally?

**Comment by nkaramolegos** [comment]
Hmm, it doesn't need to change the ESP infrastructure. I just want to run the cloud server locally. ESP can communicate again with the server but everything will be in a local network

**Comment by kbaggen** [comment]
Dear Nikos,
ok, now I better understand your question, but no........I guess others project provide this, e.g. https://www.fermentrack.com/ . 

In this project the idea is to try make everything as easy as possible and to join the various floating hydrometers into one service and to set them "free". I am ofcouse the later of "set it free" is also your wish, but I do not intend to go down the road of letting people install the cloud on thier own linux machines........nor do I know how to create such an "app".

/Klaus
