### ISSUE TITLE
After rapt firmware "20230317_094939" RAPT Pill is no longer found?

### ISSUE THREAD

**Issue by kbaggen** [kbaggen/SPINDELMATE#9]
Please notice if updating till 20230317_094939 you will break RAPT PILL and it cannot be found by SPINDELMATE. This needs to be solved in version 1.4.

**Comment by milGus** [comment]
Do you know the manufacturer data format for the RAPT Pill?

**Comment by kbaggen** [comment]
milGus, --> https://github.com/BestEnemies/pill/issues/1

**Comment by kbaggen** [comment]
I close this as version 1.4.0, now solves the issue Rapt Pill was no longer found by SPINDELMATE.

**Comment by milGus** [comment]
thanks!
